### ISSUE TITLE
Missing style for expand/collapse navbar

### ISSUE THREAD

**Issue by armano2** [facebookincubator/infima#193]
docosaurus currently implements completely custom design for expanding and collapsing navbar, that should be added in here

![image](https://user-images.githubusercontent.com/625469/144886601-05365347-1301-44ff-9c47-e9a191c4da95.png) ![image](https://user-images.githubusercontent.com/625469/144886769-4190ed4a-0a61-4b08-846f-14d580c8341f.png)![image](https://user-images.githubusercontent.com/625469/144886683-3166a592-994c-4a19-be6d-c2af9cd2c63e.png) ![image](https://user-images.githubusercontent.com/625469/144886748-9ded01ff-0d81-40c4-a021-abf1e32e5a05.png)

**Comment by slorber** [comment]
The way items are moved to Infima is quite implicit.

For me, Infima should be more like a design system, only providing design tokens, reusable well-encapsulated components and micro layouts (https://web.dev/learn/design/micro-layouts/)

IMHO the whole sidebar and its expand button is a macro layout (https://web.dev/learn/design/macro-layouts/) and should rather be kept inside Docusaurus. I believe that Infima already contains some bits of macro layouts, but I believe it was not a good idea.

Historically Infima was inspired by Bootstrap, which probably included a few macro layout items. Not sure it's a good idea to copy that part. Most modern CSS frameworks do not ship macro layouts anymore.

@lex111 may have a different opinion

**Comment by lex111** [comment]
Since I have not developed Infima from scratch, it is difficult for me to say anything about its architectural decisions. However, in my view, this framework should contain only the required set of components. The collapsible sidebar feature apparently is not on this list; it is an _optional_ feature of Docusaurus itself. Therefore, all optional design-related features implemented in Docusaurus, I would not port to Infima to make the framework as lightweight and simple as possible.

**Comment by slorber** [comment]
Thanks

We may not totally agree on the Infima exact vision, but at least we agree that this thing is better kept in the Docusaurus repo 👍

**Comment by armano2** [comment]
ok, thank you for clarification, 👍
