### ISSUE TITLE
Component suggestion: URL preview similar to GitBook

### ISSUE THREAD

**Issue by paulrberg** [facebookincubator/infima#194]
Pardon me for opening an issue for this (why not enable [discussions](https://docs.github.com/en/discussions) in this repo?)

I recently switched from GitBook to Docusaurus, and I love it so far. But there's one thing that I miss from GitBook, the URL previews:

<img width="716" alt="GitHub URL Preview" src="https://user-images.githubusercontent.com/8782666/145433609-fb398914-1508-4726-8a22-7b4a5c764971.png">

See the "hifi-finance/hifi-protocol" card? That was generated automatically after I pasted the URL in the GitBook editor. It would be super helpful if Infima provided a similar URL preview component.

I've seen the [Card](https://infima.dev/docs/components/card) component in your docs, but it's not quite the same component. That seems to be tailored for long texts and images, whereas I am referring to URL previews specifically.

**Comment by slorber** [comment]
Thanks

Was wondering what do you expect us to do exactly here.

Is the goal to just provide a new CSS card component in Infima, or to implement an end-to-end feature to support your use-case in Docusaurus, including the CSS component?

What prevents you from building this CSS component in your site directly? You could easily write a bit of CSS, create a React component and use it here and there with MDX?

**Comment by paulrberg** [comment]
> Is the goal to just provide a new CSS card component in Infima, or to implement an end-to-end feature to support your use-case in Docusaurus, including the CSS component?

The latter, although I am not sure how much that would be Docusaurus' job. I think I should cross-post this in their repo (or some other forum).

> What prevents you from building this CSS component in your site directly?

(1) A bit of laziness and (2) the fact that if this was offered by Infima/ Docusaurus by default, others won't have to write it from scratch like me.

**Comment by slorber** [comment]
IMHO this design is quite opinionated. 

If only you want this to be implemented and plan to use it (which I suspect, we shouldn't do it and you should implement it in userland, this is not hard).

Considering this design is already implementable in userland, and it's just a convenience for you to have it added to Infima, I think we'd better close this for now.

Now if you can find many Docusaurus site owners that all want this exact design in their site, or they have actually implemented this design already, we could consider adding it because it's clearly a common need. 

But I suspect it's not, and we can't increase the size/complexity of our design system just for 1 user. 

If anyone is interested in this feature, please comment below and we'll reconsider when there are enough comments.

**Comment by paulrberg** [comment]
I agree, @slorber. Thanks for the follow up. I did end up implementing a basic version of this component:

https://github.com/hifi-finance/docs/blob/168dc55ee61be26882749da6d471d67a546c2103/src/components/LinkPreview.tsx

It doesn't use OpenGraph, so it only works with a limited set of websites and icons. But it's good enough for our needs.

I wonder whether it would be more appropriate for this to be part of a community plugin for Docusaurus, similar to the KaTeX plugin that can display math formulas.

**Comment by slorber** [comment]
It doesn't even have to be coupled to Docusaurus: just publish a CSS file on npm or wherever you want and people who find it useful can use it, through ES imports or loading CSS from a CDN directly

**Comment by Josh-Cena** [comment]
> to be part of a community plugin for Docusaurus, similar to the KaTeX plugin that can display math formulas.

Just so that you know, the KaTeX rendering has nothing to do with Docusaurus. We are using out-of-the-box solutions from the Remark ecosystem.
