### ISSUE TITLE
Footer logo styling artifically restricts real uses

### ISSUE THREAD

**Issue by zpao** [facebookincubator/infima#260]
The `max-width` specified here doesn't support short & wide logos well. Specifically it looks pretty bad when trying to use the new Meta Open Source logo.

https://github.com/facebookincubator/infima/blob/12735696df7daf24f7017880df88be0b8dec38de/packages/core/styles/components/footer.pcss#L53-L56

<img width="632" alt="image" src="https://user-images.githubusercontent.com/8445/174195904-54f9ce39-1bff-453d-8eaf-23a5197362ea.png">

This is then not easy to override inside Docusaurus. The `width` property you can specify in the `logo` config isn't respected if greater than `10rem`.

You could override with inline style here (https://github.com/facebook/docusaurus/blob/6df379ca6f9510793da73183acc851b653575e6a/packages/docusaurus-theme-classic/src/theme/Footer/Logo/index.tsx#L16-L31), setting `maxWidth/Height` to the values from the config, or figure out where to drop some global override, but that's starting to feel like just fighting the system

**Comment by yangshun** [comment]
Thanks for reporting! I think we'll drop the max-width or make it configurable.

**Comment by slorber** [comment]
Changing this will impact the display of the footer logo of users websites. They may now need to add an explicit width, while it wasn't necessary before.

The max-width is useful in case the initial image is very large and the user does not provide an explicit width (which may be used by many in practice)

For example without width/max-width, this is what we could have by default: a very large OSS logo

<img width="1500" alt="CleanShot 2022-06-17 at 12 57 32@2x" src="https://user-images.githubusercontent.com/749374/174285558-3a5b4c6e-e739-483b-87ce-e45b9fde828a.png">


What I suggest is to keep it, but use `max-width: 500px` instead.

That may be a good default for many logos

<img width="1279" alt="CleanShot 2022-06-17 at 13 02 09@2x" src="https://user-images.githubusercontent.com/749374/174286168-000e5698-a52a-4916-92d2-ebf81733f4a9.png">


---

Note, another option could be something like `max-width: min(500px, 90vw);`

This permits to shrink the logo on small width so that it always stays in the viewport.

For example, if the user provides an explicit width=500 because they want a large icon on desktop, it will unfortunately not be shrinked on mobile, and it can lead to a horizontal scrollbar due to the logo overflowing.

<img width="477" alt="CleanShot 2022-06-17 at 13 06 39@2x" src="https://user-images.githubusercontent.com/749374/174286970-3b45863f-1acd-47ff-afa6-d6daaec14145.png">


But `min()` is a new CSS property, apparently not supported everywhere yet, in particular in China (see also https://github.com/facebook/docusaurus/issues/7617)

---

What I would try in the end:

```
.footer__logo {
  max-width: 500px;
}
@supports (max-width: min(0px)) {
  .footer__logo {
    max-width: min(500px, 90vw);
  }
}
```

Any opinion @yangshun ?


--- 

I'm also making sure that we can pass className/style to navbar/footer logos to override those defaults when in need.

**Comment by Josh-Cena** [comment]
I don't want us to get too constrained by Chinese browser support. The situation in China is quite unique: we have a large number of low-end devices running outdated browsers, but as of 2022, the usage of websites is on a sharp decline. I don't think many people even use browsers that much anymore. These figures are, I suppose (without any warrant), very distorted compared to their actual impact.

**Comment by slorber** [comment]
That wouldn't harm much to add that little `@supports` rule anyway 😄
